name: dwitracts
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - ipython=7.31.1
  - ipywidgets=7.6.5
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - nibabel=4.0.1
  - nilearn=0.9.1
  - numpy=1.21.6
  - pandas=1.3.5
  - pip=22.1.2
  - python=3.7.13
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - spm1d=0.4.0
  - statsmodels=0.13.2
  - tqdm=4.64.0
